name: instagible
description: Get instagram photos
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3

#  flutter_insta:
#    git:
#      url: https://github.com/Tangibleidea/flutter_insta


  # Instagram manipulation
  #flutter_insta: ^1.0.1

  # video population
  video_player: ^2.7.2

  # state management
  flutter_riverpod: ^2.4.0

  # image
  cached_network_image: ^3.3.0

  file_picker: ^4.2.0

  # resources
  cupertino_icons: ^1.0.2

  # Read PDF to text
  syncfusion_flutter_pdf: ^23.1.36
  dart_pdf_reader: ^0.4.2

  excel: ^2.1.0

  data_table_2: ^2.5.8

  chat_gpt_sdk: ^2.2.5
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/configs/.env
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:

    - family: MaruBuri
      fonts:
        - asset: assets/fonts/MaruBuri-Regular.ttf